Repository microsoft/dotnet-framework-docker, pull requests merged in 2020-12, with the labels that each got.

#687 Add microsoft/Windows-Containers link to the issues template
  .github/ISSUE_TEMPLATE/config.yml
Labels: area-external

#685 Add --no-restore option to sample Dockerfiles
  samples/aspnetapp/Dockerfile
  samples/aspnetapp/Dockerfile.windowsservercore-ltsc2016
  samples/aspnetmvcapp/Dockerfile
  samples/dotnetapp/Dockerfile
  samples/dotnetapp/Dockerfile.basic
Labels: area-samples

#677 Change branding of Windows Server, version 2009 to 20H2
  README.aspnet.md
  README.runtime.md
  README.samples.md
  README.sdk.md
  README.wcf.md
  eng/lcu-info.json
  eng/mcr-tags-metadata-templates/aspnet-tags.yml
  eng/mcr-tags-metadata-templates/runtime-tags.yml
  eng/mcr-tags-metadata-templates/samples-tags.yml
  eng/mcr-tags-metadata-templates/sdk-tags.yml
  eng/mcr-tags-metadata-templates/wcf-tags.yml
  eng/nuget-info.json
  eng/readme-templates/README.md
  manifest.json
  manifest.samples.json
  src/aspnet/3.5/windowsservercore-20H2/Dockerfile
  src/aspnet/4.8/windowsservercore-20H2/Dockerfile
  src/runtime/3.5/windowsservercore-20H2/Dockerfile
  src/runtime/4.8/windowsservercore-20H2/Dockerfile
  src/sdk/3.5/windowsservercore-20H2/Dockerfile
  src/sdk/4.8/windowsservercore-20H2/Dockerfile
  src/wcf/4.8/windowsservercore-20H2/Dockerfile
  tests/Microsoft.DotNet.Framework.Docker.Tests/AspnetImageTests.cs
  tests/Microsoft.DotNet.Framework.Docker.Tests/OsVersion.cs
  tests/Microsoft.DotNet.Framework.Docker.Tests/RuntimeOnlyImageTests.cs
  tests/Microsoft.DotNet.Framework.Docker.Tests/RuntimeSdkImageTests.cs
  tests/Microsoft.DotNet.Framework.Docker.Tests/SdkOnlyImageTests.cs
  tests/Microsoft.DotNet.Framework.Docker.Tests/WcfImageTests.cs
Labels: area-dockerfiles

#688 Updates for 12B release
  README.aspnet.md
  README.runtime.md
  README.sdk.md
  README.wcf.md
  eng/lcu-info.json
  manifest.json
  src/runtime/3.5/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.7.1/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.7.2/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.7/windowsservercore-ltsc2016/Dockerfile
Labels: area-infrastructure

#691 Remove WSC 1903 Dockerfiles due to EOL
  README.aspnet.md
  README.runtime.md
  README.samples.md
  README.sdk.md
  README.wcf.md
  eng/common/templates/stages/build-test-publish-repo.yml
  eng/lcu-info.json
  eng/mcr-tags-metadata-templates/aspnet-tags.yml
  eng/mcr-tags-metadata-templates/runtime-tags.yml
  eng/mcr-tags-metadata-templates/samples-tags.yml
  eng/mcr-tags-metadata-templates/sdk-tags.yml
  eng/mcr-tags-metadata-templates/wcf-tags.yml
  eng/nuget-info.json
  eng/readme-templates/README.md
  manifest.json
  manifest.samples.json
  src/aspnet/3.5/windowsservercore-1903/Dockerfile
  src/aspnet/4.8/windowsservercore-1903/Dockerfile
  src/runtime/3.5/windowsservercore-1903/Dockerfile
  src/runtime/4.8/windowsservercore-1903/Dockerfile
  src/sdk/3.5/windowsservercore-1903/Dockerfile
  src/sdk/4.8/windowsservercore-1903/Dockerfile
  src/wcf/4.8/windowsservercore-1903/Dockerfile
  tests/Microsoft.DotNet.Framework.Docker.Tests/AspnetImageTests.cs
  tests/Microsoft.DotNet.Framework.Docker.Tests/OsVersion.cs
  tests/Microsoft.DotNet.Framework.Docker.Tests/RuntimeOnlyImageTests.cs
  tests/Microsoft.DotNet.Framework.Docker.Tests/RuntimeSdkImageTests.cs
  tests/Microsoft.DotNet.Framework.Docker.Tests/SdkOnlyImageTests.cs
  tests/Microsoft.DotNet.Framework.Docker.Tests/WcfImageTests.cs
Labels: area-dockerfiles
