Repository microsoft/dotnet-framework-docker, pull requests merged in 2021-01, with the labels that each got.

#699 Upgrade test project to .NET 5
  tests/Microsoft.DotNet.Framework.Docker.Tests/Microsoft.DotNet.Framework.Docker.Tests.csproj
  tests/run-tests.ps1
Labels: area-infrastructure

#700 Upgrade update-dependencies to .NET 5
  eng/update-dependencies/DependencyUpdater.cs
  eng/update-dependencies/Microsoft.DotNet.Framework.UpdateDependencies.csproj
Labels: area-infrastructure

#701 Include NuGet 5.8 in SDK as additional version
  eng/models/NuGetInfo.cs
  eng/nuget-info.json
  eng/update-dependencies/DependencyUpdater.cs
  src/sdk/3.5/windowsservercore-1909/Dockerfile
  src/sdk/3.5/windowsservercore-2004/Dockerfile
  src/sdk/3.5/windowsservercore-20H2/Dockerfile
  src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile
  src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile
  src/sdk/4.8/windowsservercore-1909/Dockerfile
  src/sdk/4.8/windowsservercore-2004/Dockerfile
  src/sdk/4.8/windowsservercore-20H2/Dockerfile
  src/sdk/4.8/windowsservercore-ltsc2016/Dockerfile
  src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile
Labels: area-dockerfiles

#702 Trigger dotnet 1st-run experience in SDK
  src/sdk/3.5/windowsservercore-1909/Dockerfile
  src/sdk/3.5/windowsservercore-2004/Dockerfile
  src/sdk/3.5/windowsservercore-20H2/Dockerfile
  src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile
  src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile
  src/sdk/4.8/windowsservercore-1909/Dockerfile
  src/sdk/4.8/windowsservercore-2004/Dockerfile
  src/sdk/4.8/windowsservercore-20H2/Dockerfile
  src/sdk/4.8/windowsservercore-ltsc2016/Dockerfile
  src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile
Labels: area-dockerfiles

#705 Add infra to generate wcf Dockerfiles from templates
  eng/common/templates/variables/docker-images.yml
  eng/dockerfile-templates/Get-GeneratedDockerfiles.ps1
  eng/dockerfile-templates/wcf/Dockerfile
  manifest.json
  tests/Microsoft.DotNet.Framework.Docker.Tests/GeneratedArtifactTests.cs
Labels: area-infrastructure

#703 Refactor Dockerfiles to reduce image sizes
  src/aspnet/3.5/windowsservercore-1909/Dockerfile
  src/aspnet/3.5/windowsservercore-ltsc2016/Dockerfile
  src/aspnet/3.5/windowsservercore-ltsc2019/Dockerfile
  src/aspnet/4.6.2/windowsservercore-ltsc2016/Dockerfile
  src/aspnet/4.7.1/windowsservercore-ltsc2016/Dockerfile
  src/aspnet/4.7.2/windowsservercore-ltsc2016/Dockerfile
  src/aspnet/4.7.2/windowsservercore-ltsc2019/Dockerfile
  src/aspnet/4.7/windowsservercore-ltsc2016/Dockerfile
  src/aspnet/4.8/windowsservercore-1909/Dockerfile
  src/aspnet/4.8/windowsservercore-2004/Dockerfile
  src/aspnet/4.8/windowsservercore-20H2/Dockerfile
  src/aspnet/4.8/windowsservercore-ltsc2016/Dockerfile
  src/aspnet/4.8/windowsservercore-ltsc2019/Dockerfile
  src/runtime/3.5/windowsservercore-1909/Dockerfile
  src/runtime/3.5/windowsservercore-2004/Dockerfile
  src/runtime/3.5/windowsservercore-20H2/Dockerfile
  src/runtime/3.5/windowsservercore-ltsc2016/Dockerfile
  src/runtime/3.5/windowsservercore-ltsc2019/Dockerfile
  src/runtime/4.7.1/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.7.2/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.7.2/windowsservercore-ltsc2019/Dockerfile
  src/runtime/4.7/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.8/windowsservercore-1909/Dockerfile
  src/runtime/4.8/windowsservercore-2004/Dockerfile
  src/runtime/4.8/windowsservercore-20H2/Dockerfile
  src/runtime/4.8/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.8/windowsservercore-ltsc2019/Dockerfile
  src/sdk/3.5/windowsservercore-1909/Dockerfile
  src/sdk/3.5/windowsservercore-2004/Dockerfile
  src/sdk/3.5/windowsservercore-20H2/Dockerfile
  src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile
  src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile
  src/sdk/4.8/windowsservercore-1909/Dockerfile
  src/sdk/4.8/windowsservercore-2004/Dockerfile
  src/sdk/4.8/windowsservercore-20H2/Dockerfile
  src/sdk/4.8/windowsservercore-ltsc2016/Dockerfile
  src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile
Labels: area-dockerfiles

#709 Promote use of GH Discussions within new issue template
  .github/ISSUE_TEMPLATE/config.yml
Labels: area-infrastructure

#706 Remove usage of deprecated syntax for ENV instruction
  eng/update-dependencies/DependencyUpdater.cs
  src/aspnet/4.6.2/windowsservercore-ltsc2016/Dockerfile
  src/aspnet/4.7.1/windowsservercore-ltsc2016/Dockerfile
  src/aspnet/4.7.2/windowsservercore-ltsc2016/Dockerfile
  src/aspnet/4.7.2/windowsservercore-ltsc2019/Dockerfile
  src/aspnet/4.7/windowsservercore-ltsc2016/Dockerfile
  src/aspnet/4.8/windowsservercore-1909/Dockerfile
  src/aspnet/4.8/windowsservercore-2004/Dockerfile
  src/aspnet/4.8/windowsservercore-20H2/Dockerfile
  src/aspnet/4.8/windowsservercore-ltsc2016/Dockerfile
  src/aspnet/4.8/windowsservercore-ltsc2019/Dockerfile
  src/runtime/3.5/windowsservercore-ltsc2016/Dockerfile
  src/runtime/3.5/windowsservercore-ltsc2019/Dockerfile
  src/runtime/4.6.2/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.7.1/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.7.2/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.7.2/windowsservercore-ltsc2019/Dockerfile
  src/runtime/4.7/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.8/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.8/windowsservercore-ltsc2019/Dockerfile
  src/sdk/3.5/windowsservercore-1909/Dockerfile
  src/sdk/3.5/windowsservercore-2004/Dockerfile
  src/sdk/3.5/windowsservercore-20H2/Dockerfile
  src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile
  src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile
  src/sdk/4.8/windowsservercore-1909/Dockerfile
  src/sdk/4.8/windowsservercore-2004/Dockerfile
  src/sdk/4.8/windowsservercore-20H2/Dockerfile
  src/sdk/4.8/windowsservercore-ltsc2016/Dockerfile
  src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile
Labels: area-dockerfiles

#710 Merge changes from dev to master
  eng/models/NuGetInfo.cs
  eng/nuget-info.json
  eng/update-dependencies/DependencyUpdater.cs
  src/aspnet/3.5/windowsservercore-1909/Dockerfile
  src/aspnet/3.5/windowsservercore-ltsc2016/Dockerfile
  src/aspnet/3.5/windowsservercore-ltsc2019/Dockerfile
  src/aspnet/4.6.2/windowsservercore-ltsc2016/Dockerfile
  src/aspnet/4.7.1/windowsservercore-ltsc2016/Dockerfile
  src/aspnet/4.7.2/windowsservercore-ltsc2016/Dockerfile
  src/aspnet/4.7.2/windowsservercore-ltsc2019/Dockerfile
  src/aspnet/4.7/windowsservercore-ltsc2016/Dockerfile
  src/aspnet/4.8/windowsservercore-1909/Dockerfile
  src/aspnet/4.8/windowsservercore-2004/Dockerfile
  src/aspnet/4.8/windowsservercore-20H2/Dockerfile
  src/aspnet/4.8/windowsservercore-ltsc2016/Dockerfile
  src/aspnet/4.8/windowsservercore-ltsc2019/Dockerfile
  src/runtime/3.5/windowsservercore-1909/Dockerfile
  src/runtime/3.5/windowsservercore-2004/Dockerfile
  src/runtime/3.5/windowsservercore-20H2/Dockerfile
  src/runtime/3.5/windowsservercore-ltsc2016/Dockerfile
  src/runtime/3.5/windowsservercore-ltsc2019/Dockerfile
  src/runtime/4.6.2/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.7.1/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.7.2/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.7.2/windowsservercore-ltsc2019/Dockerfile
  src/runtime/4.7/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.8/windowsservercore-1909/Dockerfile
  src/runtime/4.8/windowsservercore-2004/Dockerfile
  src/runtime/4.8/windowsservercore-20H2/Dockerfile
  src/runtime/4.8/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.8/windowsservercore-ltsc2019/Dockerfile
  src/sdk/3.5/windowsservercore-1909/Dockerfile
  src/sdk/3.5/windowsservercore-2004/Dockerfile
  src/sdk/3.5/windowsservercore-20H2/Dockerfile
  src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile
  src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile
  src/sdk/4.8/windowsservercore-1909/Dockerfile
  src/sdk/4.8/windowsservercore-2004/Dockerfile
  src/sdk/4.8/windowsservercore-20H2/Dockerfile
  src/sdk/4.8/windowsservercore-ltsc2016/Dockerfile
  src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile
Labels: area-release

#714 Updates for 1B servicing
  README.aspnet.md
  README.runtime.md
  README.sdk.md
  README.wcf.md
  eng/lcu-info.json
  manifest.json
  src/runtime/3.5/windowsservercore-2004/Dockerfile
  src/runtime/3.5/windowsservercore-20H2/Dockerfile
  src/runtime/3.5/windowsservercore-ltsc2016/Dockerfile
  src/runtime/3.5/windowsservercore-ltsc2019/Dockerfile
  src/runtime/4.7.1/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.7.2/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.7.2/windowsservercore-ltsc2019/Dockerfile
  src/runtime/4.7/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.8/windowsservercore-2004/Dockerfile
  src/runtime/4.8/windowsservercore-20H2/Dockerfile
  src/runtime/4.8/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.8/windowsservercore-ltsc2019/Dockerfile
Labels: area-infrastructure

#715 Servicing updates for Windows Server, version 1909
  README.aspnet.md
  README.runtime.md
  README.sdk.md
  README.wcf.md
  eng/lcu-info.json
  manifest.json
  src/runtime/3.5/windowsservercore-1909/Dockerfile
  src/runtime/4.8/windowsservercore-1909/Dockerfile
Labels: area-dockerfiles

#716 Add runtime Dockerfile templates
  .github/ISSUE_TEMPLATE/releases/new-windows-release.md
  .github/ISSUE_TEMPLATE/releases/patch-tuesday-release.md
  .github/ISSUE_TEMPLATE/releases/vs-tools-release.md
  eng/dockerfile-templates/runtime/Dockerfile
  eng/dockerfile-templates/runtime/Dockerfile.ltsc2016
  eng/lcu-info.json
  eng/models/LcuInfo.cs
  eng/models/Microsoft.DotNet.Framework.Models.csproj
  eng/update-dependencies/DependencyUpdater.cs
  eng/update-dependencies/Microsoft.DotNet.Framework.UpdateDependencies.csproj
  eng/update-dependencies/Options.cs
  manifest.json
  manifest.versions.json
  src/runtime/3.5/windowsservercore-1909/Dockerfile
  src/runtime/3.5/windowsservercore-2004/Dockerfile
  src/runtime/3.5/windowsservercore-20H2/Dockerfile
  src/runtime/3.5/windowsservercore-ltsc2019/Dockerfile
  src/runtime/4.6.2/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.7.1/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.7.2/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.7/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.8/windowsservercore-1909/Dockerfile
  src/runtime/4.8/windowsservercore-2004/Dockerfile
  src/runtime/4.8/windowsservercore-20H2/Dockerfile
  src/runtime/4.8/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.8/windowsservercore-ltsc2019/Dockerfile
  tests/Microsoft.DotNet.Framework.Docker.Tests/Microsoft.DotNet.Framework.Docker.Tests.csproj
Labels: area-infrastructure

#711 Upgrade System.CommandLine version
  eng/update-dependencies/Microsoft.DotNet.Framework.UpdateDependencies.csproj
  eng/update-dependencies/NuGet.config
  eng/update-dependencies/Options.cs
  eng/update-dependencies/Program.cs
Labels: area-infrastructure
