Repository microsoft/dotnet-framework-docker, pull requests merged in 2021-09, with the labels that each got.

#816 Update download URLS for runtime installers
  eng/dockerfile-templates/runtime/Dockerfile.ltsc2016
  src/runtime/4.7.1/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.7.2/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.7/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.8/windowsservercore-ltsc2016/Dockerfile
Labels: area-infrastructure

#815 Consolidate ENV instructions in sdk Dockerfiles
  eng/dockerfile-templates/sdk/Dockerfile
  src/sdk/3.5/windowsservercore-2004/Dockerfile
  src/sdk/3.5/windowsservercore-20H2/Dockerfile
  src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile
  src/sdk/3.5/windowsservercore-ltsc2022/Dockerfile
  src/sdk/4.8/windowsservercore-2004/Dockerfile
  src/sdk/4.8/windowsservercore-20H2/Dockerfile
  src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile
  src/sdk/4.8/windowsservercore-ltsc2022/Dockerfile
Labels: area-dockerfiles

#819 Updates for Sept servicing
  README.aspnet.md
  README.runtime.md
  README.sdk.md
  README.wcf.md
  manifest.json
  manifest.versions.json
  src/runtime/3.5/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.7.1/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.7.2/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.7/windowsservercore-ltsc2016/Dockerfile
  src/sdk/3.5/windowsservercore-2004/Dockerfile
  src/sdk/3.5/windowsservercore-20H2/Dockerfile
  src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile
  src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile
  src/sdk/3.5/windowsservercore-ltsc2022/Dockerfile
  src/sdk/4.8/windowsservercore-2004/Dockerfile
  src/sdk/4.8/windowsservercore-20H2/Dockerfile
  src/sdk/4.8/windowsservercore-ltsc2016/Dockerfile
  src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile
  src/sdk/4.8/windowsservercore-ltsc2022/Dockerfile
Labels: area-infrastructure

#821 Simplify and improve samples
  samples/README.md
  samples/aspnetapp/Dockerfile.windowsservercore-ltsc2016
  samples/aspnetapp/README.md
  samples/aspnetapp/deploy-container-to-aci.md
  samples/aspnetmvcapp/README.md
  samples/aspnetmvcapp/aspnetmvcapp/Controllers/HomeController.cs
  samples/aspnetmvcapp/aspnetmvcapp/Views/Home/About.cshtml
  samples/dotnetapp/Dockerfile
  samples/dotnetapp/Dockerfile.basic
  samples/dotnetapp/Program.cs
  samples/dotnetapp/README.md
  samples/dotnetapp/dotnet-docker-unit-testing.md
  samples/dotnetapp/dotnetapp.csproj
  samples/dotnetapp/dotnetapp.sln
  samples/dotnetapp/dotnetapp/Program.cs
  samples/dotnetapp/push-image-to-acr.md
  samples/dotnetapp/push-image-to-dockerhub.md
  samples/dotnetapp/tests/ConsoleUtilsTests.cs
  samples/dotnetapp/tests/StringUtilsTests.cs
  samples/dotnetapp/tests/tests.csproj
  samples/dotnetapp/utils/ConsoleUtils.cs
  samples/dotnetapp/utils/StringUtils.cs
  samples/dotnetapp/utils/utils.csproj
Labels: area-samples
