Repository microsoft/dotnet-framework-docker, pull requests merged in 2023-07, with the labels that each got.

#1074 Updates to include .NET Fx 4.8/4.8.1 June sec patch
  README.aspnet.md
  README.runtime.md
  README.sdk.md
  README.wcf.md
  eng/common/templates/jobs/build-images.yml
  eng/common/templates/stages/build-test-publish-repo.yml
  manifest.datestamps.json
  src/aspnet/3.5/windowsservercore-ltsc2022/Dockerfile
  src/aspnet/4.8.1/windowsservercore-ltsc2022/Dockerfile
  src/aspnet/4.8/windowsservercore-ltsc2016/Dockerfile
  src/aspnet/4.8/windowsservercore-ltsc2019/Dockerfile
  src/aspnet/4.8/windowsservercore-ltsc2022/Dockerfile
  src/runtime/3.5/windowsservercore-ltsc2022/Dockerfile
  src/runtime/4.8.1/windowsservercore-ltsc2022/Dockerfile
  src/runtime/4.8/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.8/windowsservercore-ltsc2019/Dockerfile
  src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile
  src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile
  src/sdk/3.5/windowsservercore-ltsc2022/Dockerfile
  src/sdk/4.8.1/windowsservercore-ltsc2022/Dockerfile
  src/sdk/4.8/windowsservercore-ltsc2016/Dockerfile
  src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile
  src/sdk/4.8/windowsservercore-ltsc2022/Dockerfile
  src/wcf/4.8.1/windowsservercore-ltsc2022/Dockerfile
  src/wcf/4.8/windowsservercore-ltsc2016/Dockerfile
  src/wcf/4.8/windowsservercore-ltsc2019/Dockerfile
  src/wcf/4.8/windowsservercore-ltsc2022/Dockerfile
Labels: area-infrastructure

#1077 Pin to specific version of ManifestGeneratorTask
  eng/common/templates/jobs/build-images.yml
Labels: area-infrastructure

#1080 .NET Framework Servicing updates for July 2023
  README.aspnet.md
  README.runtime.md
  README.sdk.md
  README.wcf.md
  manifest.datestamps.json
  manifest.versions.json
  src/aspnet/3.5/windowsservercore-ltsc2016/Dockerfile
  src/aspnet/3.5/windowsservercore-ltsc2019/Dockerfile
  src/aspnet/3.5/windowsservercore-ltsc2022/Dockerfile
  src/aspnet/4.6.2/windowsservercore-ltsc2016/Dockerfile
  src/aspnet/4.7.1/windowsservercore-ltsc2016/Dockerfile
  src/aspnet/4.7.2/windowsservercore-ltsc2016/Dockerfile
  src/aspnet/4.7.2/windowsservercore-ltsc2019/Dockerfile
  src/aspnet/4.7/windowsservercore-ltsc2016/Dockerfile
  src/aspnet/4.8.1/windowsservercore-ltsc2022/Dockerfile
  src/aspnet/4.8/windowsservercore-ltsc2016/Dockerfile
  src/aspnet/4.8/windowsservercore-ltsc2019/Dockerfile
  src/aspnet/4.8/windowsservercore-ltsc2022/Dockerfile
  src/runtime/3.5/windowsservercore-ltsc2016/Dockerfile
  src/runtime/3.5/windowsservercore-ltsc2019/Dockerfile
  src/runtime/3.5/windowsservercore-ltsc2022/Dockerfile
  src/runtime/4.7.1/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.7.2/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.7/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.8.1/windowsservercore-ltsc2022/Dockerfile
  src/runtime/4.8/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.8/windowsservercore-ltsc2019/Dockerfile
  src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile
  src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile
  src/sdk/3.5/windowsservercore-ltsc2022/Dockerfile
  src/sdk/4.8.1/windowsservercore-ltsc2022/Dockerfile
  src/sdk/4.8/windowsservercore-ltsc2016/Dockerfile
  src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile
  src/sdk/4.8/windowsservercore-ltsc2022/Dockerfile
  src/wcf/4.6.2/windowsservercore-ltsc2016/Dockerfile
  src/wcf/4.7.1/windowsservercore-ltsc2016/Dockerfile
  src/wcf/4.7.2/windowsservercore-ltsc2016/Dockerfile
  src/wcf/4.7.2/windowsservercore-ltsc2019/Dockerfile
  src/wcf/4.7/windowsservercore-ltsc2016/Dockerfile
  src/wcf/4.8.1/windowsservercore-ltsc2022/Dockerfile
  src/wcf/4.8/windowsservercore-ltsc2016/Dockerfile
  src/wcf/4.8/windowsservercore-ltsc2019/Dockerfile
  src/wcf/4.8/windowsservercore-ltsc2022/Dockerfile
Labels: area-dockerfiles

#1082 Re-enable prebuild validation step
  eng/common/templates/jobs/build-images.yml
  eng/common/templates/stages/build-test-publish-repo.yml
Labels: area-infrastructure

#1085 Fix related repositories MCR URLs
  .mcr/portal/README.aspnet.portal.md
  .mcr/portal/README.runtime.portal.md
  .mcr/portal/README.samples.portal.md
  .mcr/portal/README.sdk.portal.md
  .mcr/portal/README.wcf.portal.md
  eng/readme-templates/Url.md
Labels: area-documentation
