Repository microsoft/dotnet-framework-docker, pull requests merged in 2023-01, with the labels that each got.

#1035 Upgrade jQuery version in samples
  samples/aspnetapp/aspnetapp/Scripts/jquery-3.4.1.min.js
  samples/aspnetapp/aspnetapp/Scripts/jquery-3.4.1.min.map
  samples/aspnetapp/aspnetapp/Scripts/jquery-3.4.1.slim.min.js
  samples/aspnetapp/aspnetapp/Scripts/jquery-3.4.1.slim.min.map
  samples/aspnetapp/aspnetapp/Scripts/jquery-3.5.1.intellisense.js
  samples/aspnetapp/aspnetapp/Scripts/jquery-3.5.1.js
  samples/aspnetapp/aspnetapp/Scripts/jquery-3.5.1.min.js
  samples/aspnetapp/aspnetapp/Scripts/jquery-3.5.1.min.map
  samples/aspnetapp/aspnetapp/Scripts/jquery-3.5.1.slim.js
  samples/aspnetapp/aspnetapp/Scripts/jquery-3.5.1.slim.min.js
  samples/aspnetapp/aspnetapp/Scripts/jquery-3.5.1.slim.min.map
  samples/aspnetapp/aspnetapp/Web.config
  samples/aspnetapp/aspnetapp/aspnetapp.csproj
  samples/aspnetapp/aspnetapp/packages.config
  samples/aspnetmvcapp/aspnetmvcapp/Scripts/jquery-3.4.1.min.js
  samples/aspnetmvcapp/aspnetmvcapp/Scripts/jquery-3.4.1.min.map
  samples/aspnetmvcapp/aspnetmvcapp/Scripts/jquery-3.4.1.slim.min.js
  samples/aspnetmvcapp/aspnetmvcapp/Scripts/jquery-3.4.1.slim.min.map
  samples/aspnetmvcapp/aspnetmvcapp/Scripts/jquery-3.5.1.intellisense.js
  samples/aspnetmvcapp/aspnetmvcapp/Scripts/jquery-3.5.1.js
  samples/aspnetmvcapp/aspnetmvcapp/Scripts/jquery-3.5.1.min.js
  samples/aspnetmvcapp/aspnetmvcapp/Scripts/jquery-3.5.1.min.map
  samples/aspnetmvcapp/aspnetmvcapp/Scripts/jquery-3.5.1.slim.js
  samples/aspnetmvcapp/aspnetmvcapp/Scripts/jquery-3.5.1.slim.min.js
  samples/aspnetmvcapp/aspnetmvcapp/Scripts/jquery-3.5.1.slim.min.map
  samples/aspnetmvcapp/aspnetmvcapp/Web.config
  samples/aspnetmvcapp/aspnetmvcapp/aspnetmvcapp.csproj
  samples/aspnetmvcapp/aspnetmvcapp/packages.config
Labels: area-samples

#1036 Remove .NET Core 3.1 from SDK Dockerfiles
  eng/dockerfile-templates/sdk/Dockerfile
  eng/dockerfile-templates/sdk/Dockerfile.ltsc2016
  src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile
  src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile
  src/sdk/3.5/windowsservercore-ltsc2022/Dockerfile
  src/sdk/4.8.1/windowsservercore-ltsc2022/Dockerfile
  src/sdk/4.8/windowsservercore-ltsc2016/Dockerfile
  src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile
  src/sdk/4.8/windowsservercore-ltsc2022/Dockerfile
Labels: area-dockerfiles

#1039 Updates for 1B release
  README.aspnet.md
  README.runtime.md
  README.sdk.md
  README.wcf.md
  manifest.datestamps.json
  manifest.versions.json
  src/aspnet/3.5/windowsservercore-ltsc2016/Dockerfile
  src/aspnet/3.5/windowsservercore-ltsc2022/Dockerfile
  src/aspnet/4.7.1/windowsservercore-ltsc2016/Dockerfile
  src/aspnet/4.7.2/windowsservercore-ltsc2016/Dockerfile
  src/aspnet/4.7/windowsservercore-ltsc2016/Dockerfile
  src/runtime/3.5/windowsservercore-ltsc2016/Dockerfile
  src/runtime/3.5/windowsservercore-ltsc2022/Dockerfile
  src/runtime/4.7.1/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.7.2/windowsservercore-ltsc2016/Dockerfile
  src/runtime/4.7/windowsservercore-ltsc2016/Dockerfile
  src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile
  src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile
  src/sdk/3.5/windowsservercore-ltsc2022/Dockerfile
  src/sdk/4.8.1/windowsservercore-ltsc2022/Dockerfile
  src/sdk/4.8/windowsservercore-ltsc2016/Dockerfile
  src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile
  src/sdk/4.8/windowsservercore-ltsc2022/Dockerfile
  src/wcf/4.7.1/windowsservercore-ltsc2016/Dockerfile
  src/wcf/4.7.2/windowsservercore-ltsc2016/Dockerfile
  src/wcf/4.7/windowsservercore-ltsc2016/Dockerfile
Labels: area-infrastructure

#1041 Update eng/common with latest and update to .NET 7.0
  eng/common/Install-DotNetSdk.ps1
  eng/common/templates/variables/docker-images.yml
  eng/update-dependencies/Microsoft.DotNet.Framework.UpdateDependencies.csproj
  tests/Microsoft.DotNet.Framework.Docker.Tests/Microsoft.DotNet.Framework.Docker.Tests.csproj
Labels: area-infrastructure
